@usersp = http://localhost:3000/user/usersp
@login = http://localhost:3000/user/logIn
@getproductos= http://localhost:3000/user/getproductos
@createProducto = http://localhost:3000/user/createProducto

@updateProducto = http://localhost:3000/user/updateProducto/1

@Cursar = http://localhost:3000/user/Cursar

@getproductosId = http://localhost:3000/user/getMproductosByID/1

POST {{login}}
Content-Type: application/json

{
    "dni":"6667",
    "contra":"1234"
}

###
POST {{usersp}}
#header
Content-Type: application/json
#body

{
    "dni":"66677",
    "nombre":"juansito3",
    "contra":"1234"
}

###

GET {{getproductos}}
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkbmkiOiI2NjY3IiwiaWF0IjoxNzI5Njg5OTg0LCJleHAiOjMuMzMzMzMzMzMzMzMzMzM0ZSsyOX0.z-SvlpiWvdz7O1vHJquHt_KWgU1X-GlcptFY56YcWuo
###

POST {{createProducto}}
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkbmkiOiI2NjY3IiwiaWF0IjoxNzMwMjkxMjQ4LCJleHAiOjMuMzMzMzMzMzMzMzMzMzM0ZSsyOX0.hs8io7NBdcwP3R_BS4aHEvKh5D2lWKvlcmHNenehbu8

{
    "nombre_poducto": "Cartera Juanita Jo5",
    "precio":"123",
    "stock":"18"

}

##########################################################

PUT {{updateProducto}}
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkbmkiOiI2NjY3IiwiaWF0IjoxNzMwMjkxMjQ4LCJleHAiOjMuMzMzMzMzMzMzMzMzMzM0ZSsyOX0.hs8io7NBdcwP3R_BS4aHEvKh5D2lWKvlcmHNenehbu8

{
    "nombre_poducto": "Cartera Juanita Jo",
    "precio":"123444",
    "stock":"4"
}


##############################################
####Podria usarlo paa asociar productos a usuarios, 
POST {{Cursar}}  
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkbmkiOiI2NjY3IiwiaWF0IjoxNzI5Njg5OTg0LCJleHAiOjMuMzMzMzMzMzMzMzMzMzM0ZSsyOX0.z-SvlpiWvdz7O1vHJquHt_KWgU1X-GlcptFY56YcWuo

{
    "dni": "666",
    "materias_ids": [1, 2 ]
}


#####################################################

GET {{getproductosId}}
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkbmkiOiI2NjY3IiwiaWF0IjoxNzI5Njg5OTg0LCJleHAiOjMuMzMzMzMzMzMzMzMzMzM0ZSsyOX0.z-SvlpiWvdz7O1vHJquHt_KWgU1X-GlcptFY56YcWuo



