@usersp = http://localhost:3000/user/usersp
@login = http://localhost:3000/user/logIn
@getMaterias = http://localhost:3000/user/getMaterias
@createMateria = http://localhost:3000/user/createMateria
@Cursar = http://localhost:3000/user/Cursar

@getMateriaId = http://localhost:3000/user/getMateriasByID/1

POST {{login}}
Content-Type: application/json

{
    "dni":"666",
    "contra":"1234"
}

###
POST {{usersp}}
#header
Content-Type: application/json
#body

{
    "dni":"666",
    "nombre":"juan",
    "contra":"1234"
}

###

GET {{getMaterias}}
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkbmkiOiI0IiwiaWF0IjoxNzE4NzE0NTA4LCJleHAiOjMuMzMzMzMzMzMzMzMzMzM0ZSsyOX0.pZbSmprQIlPzOYcY_g4AwsR0GbRdQ1AmJOpCgGgRjvM
###

POST {{createMateria}}
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkbmkiOiI0IiwiaWF0IjoxNzE4NzE0NTA4LCJleHAiOjMuMzMzMzMzMzMzMzMzMzM0ZSsyOX0.pZbSmprQIlPzOYcY_g4AwsR0GbRdQ1AmJOpCgGgRjvM

{
    "nombre_materia": "matematicas"

}


##############################################

POST {{Cursar}}
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkbmkiOiI0IiwiaWF0IjoxNzE4NzY5MjYwLCJleHAiOjMuMzMzMzMzMzMzMzMzMzM0ZSsyOX0.IvNHjeTP_evH1LJBqEybd8mhPbkN6GvmTPbFGftvTz4

{
    "dni": "1",
    "materias_ids": [1, 2 ]
}


#####################################################33

GET {{getMateriaId}}
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkbmkiOiI0IiwiaWF0IjoxNzE4NzY5MjYwLCJleHAiOjMuMzMzMzMzMzMzMzMzMzM0ZSsyOX0.IvNHjeTP_evH1LJBqEybd8mhPbkN6GvmTPbFGftvTz4



